#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
# 
# chkconfig:   - 85 15
# description: redis server
# processname: redis
# config:      /data/etc/redis/6379/redis.conf
# pidfile:     /data/run/redis-6379.pid
# Source function library.

REDISPORT=6379
EXEC=/usr/local/redis-3.0.3/bin/redis-server
CLIEXEC=/usr/local/redis-3.0.3/bin/redis-cli

PIDFILE=/data/run/redis-${REDISPORT}.pid
CONF="/data/etc/redis/${REDISPORT}/redis.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
